Repository tabuckner/material-dayjs-adapter, pull requests merged in 2020-03, with the labels that each got.

#9 init parser method abstracted from constructor to avoid TS error
  projects/material-dayjs-adapter/src/lib/adapter/dayjs-date-adapter.ts
Labels: bug, enhancement

#10 Accessor ambient context
  projects/material-dayjs-adapter/README.md
  projects/material-dayjs-adapter/src/lib/adapter/dayjs-date-adapter.ts
Labels: documentation

#12 Develop
  package-lock.json
  package.json
  projects/material-dayjs-adapter/README.md
  projects/material-dayjs-adapter/src/lib/adapter/dayjs-date-adapter.ts
  yarn.lock
Labels: bug, documentation, enhancement

#13 Cd
  .travis.yml
  package.json
  yarn.lock
Labels: enhancement

#14 Develop
  .travis.yml
  package.json
  projects/material-dayjs-adapter/README.md
  yarn.lock
Labels: documentation, enhancement

#7 Schematics and Angular 8+ Support
  angular.json
  package-lock.json
  package.json
  projects/example-material-dayjs-adapter/src/app/app.component.ts
  projects/example-material-dayjs-adapter/src/app/app.module.ts
  projects/example-material-dayjs-adapter/src/main.ts
  projects/example-material-dayjs-adapter/tsconfig.app.json
  projects/material-dayjs-adapter/README.md
  projects/material-dayjs-adapter/package.json
  projects/material-dayjs-adapter/schematics/collection.json
  projects/material-dayjs-adapter/schematics/date-formats/files/mat-dayjs-date-formats.ts
  projects/material-dayjs-adapter/schematics/date-formats/index.ts
  projects/material-dayjs-adapter/schematics/date-formats/schema.json
  projects/material-dayjs-adapter/schematics/date-formats/schema.ts
  projects/material-dayjs-adapter/schematics/ng-add/index.ts
  projects/material-dayjs-adapter/schematics/ng-update/index.ts
  projects/material-dayjs-adapter/src/lib/adapter/dayjs-date-adapter.ts
  projects/material-dayjs-adapter/src/lib/adapter/index.ts
  projects/material-dayjs-adapter/tsconfig.lib.json
  projects/material-dayjs-adapter/tsconfig.lib.prod.json
  projects/material-dayjs-adapter/tsconfig.schematics.json
  projects/material-dayjs-adapter/yarn.lock
  yarn.lock
Labels: documentation, enhancement
